# ==================== DataSource ====================
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=${DB_USERNAME:root}
quarkus.datasource.password=${DB_PASSWORD:}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:mysql://localhost:3306/restaurant_db}
# ==================== Hibernate ORM ====================
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql

# ==================== HTTP & CORS ====================
quarkus.http.port=${APP_PORT:8080}
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.exposed-headers=location,info
quarkus.http.cors.access-control-max-age=24H
quarkus.http.cors.access-control-allow-credentials=false

# ==================== Logging ====================
quarkus.log.level=INFO
quarkus.log.category."org.hibernate.SQL".level=DEBUG

# ==================== Security (Elytron JDBC) ====================
quarkus.security.jdbc.enabled=true
quarkus.security.jdbc.principal-query.sql=SELECT password, role FROM staff WHERE username=?

quarkus.security.jdbc.principal-query.clear-password-mapper.enabled=false
quarkus.security.jdbc.principal-query.bcrypt-password-mapper.enabled=true
quarkus.security.jdbc.principal-query.bcrypt-password-mapper.password-index=1
quarkus.security.jdbc.role-query.sql=SELECT role FROM staff WHERE username=?

quarkus.security.jdbc.principal-query.attribute-mappings[0].index=2
quarkus.security.jdbc.principal-query.attribute-mappings[0].to=groups


smallrye.jwt.sign.key.location=PrivateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem

mp.jwt.verify.issuer=${JWT_ISSUER:restaurant-app}